"""your message

Revision ID: dd5e9fe77fa1
Revises: 6a7e02dd80a5
Create Date: 2025-06-26 04:18:22.569862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5e9fe77fa1'
down_revision = '6a7e02dd80a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
